# Generated by Django 6.1.1 on 2026-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maprouter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_accuracy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
